/* Pages. Each preset is a starting chart; every control on the right can change it. */
'use strict';
const VIEWS = [
  { group: 'Overview', id: 'map', title: 'Plot map', ds: 'plots', mode: 'map',
    note: 'Plot layout for the season. Choose what colors the plots on the left. Hover a plot for its values.',
    st: { type: 'bar', x: 'Farm', ys: ['User_Average_Yield_bu_ac'], agg: 'mean', color: 'Track', filters: { Year: [2025] } } },
  { group: 'Overview', id: 'explore', title: 'Build your own chart', special: 'explore',
    note: 'Pick any dataset, then choose X, Y, grouping, chart type and filters on the right.' },

  { group: 'Plots and hybrids', id: 'plots_yield', title: 'Plot summary', ds: 'plots',
    note: 'One row per plot, from the compiled plot data. Default: user hybrid yield by farm.',
    st: { type: 'bar', x: 'Farm', ys: ['User_Average_Yield_bu_ac'], agg: 'mean', color: 'Track', filters: { Year: [2025] } } },
  { group: 'Plots and hybrids', id: 'hybrid_seed', title: 'Hybrid and seeding rate', ds: 'plots',
    note: 'Seeding rate by farm, colored by hybrid.',
    st: { type: 'bar', x: 'Farm', ys: ['SeedingRate'], agg: 'mean', color: 'Hybrid', filters: { Year: [2025] } } },

  { group: 'Plots and hybrids', id: 'stand', title: 'Stand counts (2026)', ds: 'stand_count',
    note: 'Plants counted on 6/9/2026 compared with the seeding rate each team chose.',
    st: { type: 'bar', x: 'Farm', ys: ['Seeding rate', 'Stand count'], agg: 'mean', color: null, filters: {} } },
  { group: 'Irrigation and nitrogen', id: 'water_q', title: 'Irrigation water quality (2026)', ds: 'water_quality',
    note: 'Irrigation water analysis, July 2026. Values reported as below detection are in the table as text.',
    st: { type: 'hbar', x: 'Constituent', ys: ['Result'], agg: 'mean', color: 'Unit', filters: { Unit: ['mg/L'] } } },
  { group: 'Irrigation and nitrogen', id: 'irr_cum', title: 'Irrigation over the season', ds: 'irrigation_events',
    note: 'Cumulative irrigation by farm (mean of the farm’s plots on each date). Turn off "Running total" to see each event.',
    st: { type: 'line', x: 'Date', ys: ['Irrigation_in'], agg: 'mean', color: 'Farm', cumulative: true, filters: { Year: [2025] } } },
  { group: 'Irrigation and nitrogen', id: 'irr_farm', title: 'Irrigation total by farm', ds: 'plots',
    note: 'Total irrigation per plot including fertigation water (plot data sheet), averaged over each farm’s plots.',
    st: { type: 'bar', x: 'Farm', ys: ['IA_Total_Irr_inc_Fer_in'], agg: 'mean', color: 'Track', filters: { Year: [2025] } } },
  { group: 'Irrigation and nitrogen', id: 'irr_events', title: 'Irrigation events by plot', ds: 'irrigation_events',
    note: 'Each event stacked, per plot. Filter a farm or block on the right.',
    st: { type: 'stacked', x: 'Plot', ys: ['Irrigation_in'], agg: 'sum', color: 'Date', filters: { Year: [2025], Farm: [1, 2, 3, 4, 5] } } },
  { group: 'Irrigation and nitrogen', id: 'n_farm', title: 'Nitrogen by farm and application', ds: 'nitrogen_events',
    note: 'Each application (source column) averaged over the farm’s plots and stacked, so the bar height is the season total per plot.',
    st: { type: 'stacked', x: 'Farm', ys: ['N_lb_ac'], agg: 'mean', color: 'Label', filters: { Year: [2025] } } },
  { group: 'Irrigation and nitrogen', id: 'n_cum', title: 'Nitrogen over the season', ds: 'nitrogen_events',
    note: 'Cumulative in-season N (sidedress and fertigation with a date) by farm. Preplant has no date and is not on this chart.',
    st: { type: 'line', x: 'Date', ys: ['N_lb_ac'], agg: 'mean', color: 'Farm', cumulative: true, filters: { Year: [2025] } } },

  { group: 'Soil', id: 'soil_n', title: 'Soil nitrate by depth', ds: 'soil_lab',
    note: 'Soil NO3-N (lb/ac) by farm, stacked by depth, before planting.',
    st: { type: 'stacked', x: 'Farm', ys: ['Value'], agg: 'mean', color: 'Depth_in', filters: { Year: [2025], Variable: ['NO3-N'], Unit: ['lb/ac'], Season: ['Spring (before planting)'] } } },
  { group: 'Soil', id: 'soil_any', title: 'Soil test values', ds: 'soil_lab',
    note: 'Any soil test value by plot. Choose the variable and depth on the right.',
    st: { type: 'bar', x: 'Plot', ys: ['Value'], agg: 'mean', color: 'Track', filters: { Year: [2025], Variable: ['pH'], Depth_in: ['0-8'] } } },
  { group: 'Soil moisture', id: 'sm', title: 'Soil moisture probes', special: 'sm',
    note: 'Probe readings by depth for one plot, with irrigation and rain. Styled after the CropX dashboard.' },
  { group: 'Soil moisture', id: 'neutron', title: 'Neutron probe (2025)', ds: 'neutron_probe',
    note: 'Volumetric water content by depth on each reading date.',
    st: { type: 'line', x: 'Date', ys: ['VWC'], agg: 'mean', color: 'Depth_cm', filters: { Plot: ['10C'] } } },

  { group: 'Plant tissue', id: 'tissue', title: 'Plant tissue N', ds: 'plant_tissue',
    note: 'Tissue N (%) by farm and sampling date.',
    st: { type: 'bar', x: 'Farm', ys: ['Value'], agg: 'mean', color: 'Date', filters: { Year: [2025], Variable: ['N'] } } },

  { group: 'Yield', id: 'yield_farm', title: 'Yield by farm', ds: 'yield_strips',
    note: 'Harvest strip yields averaged by farm, user and reference hybrid side by side.',
    st: { type: 'bar', x: 'Farm', ys: ['Yield_bu_ac'], agg: 'mean', color: 'Hybrid', filters: { Year: [2025] } } },
  { group: 'Yield', id: 'yield_box', title: 'Yield spread by farm', ds: 'yield_strips',
    note: 'Box plot of the harvest strips in each farm (min, quartiles, max).',
    st: { type: 'box', x: 'Farm', ys: ['Yield_bu_ac'], agg: 'none', color: null, filters: { Year: [2025], Hybrid: ['User'] } } },
  { group: 'Yield', id: 'yield_irr', title: 'Yield and irrigation by plot', ds: 'plots',
    note: 'Each point is a plot.',
    st: { type: 'scatter', x: 'IA_Total_Irr_inc_Fer_in', ys: ['User_Average_Yield_bu_ac'], agg: 'none', color: 'Track', filters: { Year: [2025] } } },

  { group: 'Remote sensing', id: 'vi', title: 'Vegetation indices over time', ds: 'vegetation_indices',
    note: 'Plot mean index on each image date, averaged by track. Change the grouping to Farm or Plot.',
    st: { type: 'line', x: 'Date', ys: ['Value'], agg: 'mean', color: 'Track', filters: { Year: [2025], Index: ['NDVI'] } } },

  { group: 'Weather and ET', id: 'weather_t', title: 'Daily temperature', ds: 'weather_daily',
    note: 'CoAgMET FTC03 daily max and min temperature.',
    st: { type: 'line', x: 'Date', ys: ['Value'], agg: 'mean', color: 'Variable', filters: { Year: [2025], Station: ['CoAgMET FTC03'], Variable: ['Max temperature', 'Min temperature'] } } },
  { group: 'Weather and ET', id: 'weather_p', title: 'Rain and ET', ds: 'weather_daily',
    note: 'Running totals of rain and reference ET at CoAgMET FTC03.',
    st: { type: 'line', x: 'Date', ys: ['Value'], agg: 'mean', color: 'Variable', cumulative: true, filters: { Year: [2025], Station: ['CoAgMET FTC03'], Variable: ['Precipitation', 'ETo (grass)', 'ETr (alfalfa)'] } } },
  { group: 'Weather and ET', id: 'arable', title: 'Arable stations', ds: 'weather_daily',
    note: 'Daily crop ET from the Arable Mark stations in the plots.',
    st: { type: 'line', x: 'Date', ys: ['Value'], agg: 'mean', color: 'Station', filters: { Year: [2025], Variable: ['Crop ET (ETc)'] } } },

  { group: 'Economics and marketing', id: 'profit', title: 'Net profit by farm', ds: 'economics_farm',
    note: 'Net profit per acre by farm.',
    st: { type: 'bar', x: 'Farm', ys: ['Net profit ($/ac)'], agg: 'sum', color: 'Track', filters: { Year: [2025] } } },
  { group: 'Economics and marketing', id: 'revenue', title: 'Revenue and cost by farm', ds: 'economics_farm',
    note: 'Revenue parts stacked, next to production cost.',
    st: { type: 'bar', x: 'Farm', ys: ['Grain revenue ($/ac)', 'Water sale ($/ac)', 'Indemnities ($/ac)', 'Cost ($/ac)'], agg: 'sum', color: null, filters: { Year: [2025] } } },
  { group: 'Economics and marketing', id: 'insurance', title: 'Insurance plans', ds: 'insurance',
    note: 'Share of farms by insurance plan type, one pie per year.',
    st: { type: 'pie', x: 'Plan type', ys: ['Coverage (%)'], agg: 'count', color: 'Year', filters: {} } },
  { group: 'Economics and marketing', id: 'coverage', title: 'Insurance coverage level', ds: 'insurance',
    note: 'Share of farms by coverage percent, one pie per year.',
    st: { type: 'pie', x: 'Coverage (%)', ys: ['Premium ($/ac)'], agg: 'count', color: 'Year', filters: {} } },
  { group: 'Economics and marketing', id: 'contracts', title: 'Marketing contract types', ds: 'marketing_contracts',
    note: 'Bushels contracted by contract type, one pie per year.',
    st: { type: 'pie', x: 'Contract', ys: ['Quantity (bu)'], agg: 'sum', color: 'Year', filters: {} } },
  { group: 'Economics and marketing', id: 'contracts_time', title: 'Contracts over time', ds: 'marketing_contracts',
    note: 'Each contract placed: date and price. Basis contracts show the basis, so filter by contract type.',
    st: { type: 'scatter', x: 'Date', ys: ['Price ($/bu)'], agg: 'none', color: 'Contract', filters: { Year: [2025], Contract: ['Forward', 'Simple Hedge'] } } },
  { group: 'Economics and marketing', id: 'futures', title: 'December corn futures', ds: 'futures',
    note: 'Daily close of the December contract for each season.',
    st: { type: 'line', x: 'Date', ys: ['Close'], agg: 'none', color: 'Contract', filters: {} } },

  { group: 'Data', id: 'downloads', title: 'Download data', special: 'downloads',
    note: 'Every dataset on this site, as CSV or Excel. For the full workbooks, see the data package.' },
];
